# Generated by Django 5.2.15 on 2026-07-08 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_paid_at_order_razorpay_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged'), ('WRONG_ITEM', 'Wrong Item'), ('DEFECTIVE', 'Defective'), ('NOT_AS_DESCRIBED', 'Not as Described'), ('QUALITY_ISSUE', 'Quality Issue'), ('SIZE_ISSUE', 'Size Issue'), ('CHANGED_MIND', 'Changed Mind'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REFUND_PROCESSING', 'Refund Processing'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inventory_restored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='orders.orderitem')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_returns', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='return_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='returns.returnrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status'], name='returns_ret_status_d3fc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['created_at'], name='returns_ret_created_a48112_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['user'], name='returns_ret_user_id_561010_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order'], name='returns_ret_order_i_30fb33_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REQUESTED', 'UNDER_REVIEW', 'APPROVED', 'REFUND_PROCESSING'])), fields=('order', 'order_item'), name='unique_active_return_request'),
        ),
    ]
