# Generated by Django 5.2.15 on 2026-07-07 11:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Recipient's full name.", max_length=150)),
                ('phone', models.CharField(help_text='Contact phone number for shipping updates.', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number.')])),
                ('address_line_1', models.CharField(help_text='Flat, House no., Building, Company, Apartment', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Area, Street, Sector, Village', max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, help_text='E.g. near hospital, mall, school etc.', max_length=100, null=True)),
                ('city', models.CharField(help_text='City or Town name.', max_length=100)),
                ('state', models.CharField(help_text='State, Province, or Region.', max_length=100)),
                ('country', models.CharField(default='India', help_text='Country name.', max_length=100)),
                ('postal_code', models.CharField(help_text='ZIP or PIN code.', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5,6}$', message='Enter a valid postal code.')])),
                ('address_type', models.CharField(choices=[('HOME', 'Home (All-day delivery)'), ('WORK', 'Work (9 AM - 5 PM delivery)'), ('OTHER', 'Other')], default='HOME', help_text='Category of address (Home, Work, or Other).', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Designates this address as the default shipping destination.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this address is active or soft-deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user profile associated with this address.', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Address',
                'verbose_name_plural': 'User Addresses',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
