# Generated by Django 5.2.15 on 2026-07-06 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_items_cart'),
        ('shop', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart_items',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterModelOptions(
            name='cart_list',
            options={'ordering': ('-date_added',), 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='active',
            field=models.BooleanField(default=True, help_text='Is this item still active in the cart?'),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='cart',
            field=models.ForeignKey(default=1, help_text='The cart this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart_list'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='product',
            field=models.ForeignKey(help_text='The product being purchased.', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.IntegerField(help_text='Number of items added.'),
        ),
        migrations.AlterField(
            model_name='cart_list',
            name='cart_id',
            field=models.CharField(help_text='The session key associated with this cart.', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='cart_list',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='When this cart was created.'),
        ),
    ]
